import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface)',
        'surface-container-lowest': 'var(--color-input-bg)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-high)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-tint': 'var(--color-primary)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': '#a3d0bf',
        'on-primary-fixed': '#002118',
        'on-primary-fixed-variant': '#244e41',
        secondary: 'var(--color-secondary)',
        'on-secondary': '#ffffff',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary-fixed': '#ffdea6',
        'secondary-fixed-dim': '#f7bd48',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5d4200',
        tertiary: '#2e2d29',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#44433e',
        'on-tertiary-container': '#b2b0a9',
        'tertiary-fixed': '#e6e2db',
        'tertiary-fixed-dim': '#c9c6c0',
        'on-tertiary-fixed': '#1c1c18',
        'on-tertiary-fixed-variant': '#484742',
        error: 'var(--color-error)',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: 'var(--color-background)',
        'on-background': 'var(--color-on-surface)',
        'surface-variant': 'var(--color-surface-container-high)',
        'aged-paper': 'var(--color-aged-paper)',
        'elevated-panels': 'var(--color-surface-elevated)',
        parchment: 'var(--color-parchment)',
        'forest-green': 'var(--color-primary)',
        'gilt-gold': 'var(--color-gilt)',
        ink: 'var(--color-on-surface)',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        serif: ['Lora', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'body-lg': ['Literata', 'Georgia', 'serif'],
        'body-md': ['Literata', 'Georgia', 'serif'],
        'display-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
        'label-sm': ['Literata', 'Georgia', 'serif'],
        'code-sm': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        editor: ['Lora', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        content: '800px',
      },
    },
  },
  plugins: [],
}

export default config
