import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#414845',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#717975',
        'outline-variant': '#c0c8c3',
        'surface-tint': '#3c6658',
        primary: '#033327',
        'on-primary': '#ffffff',
        'primary-container': '#1f4a3d',
        'on-primary-container': '#8cb9a8',
        'inverse-primary': '#a3d0bf',
        'primary-fixed': '#beecda',
        'primary-fixed-dim': '#a3d0bf',
        'on-primary-fixed': '#002118',
        'on-primary-fixed-variant': '#244e41',
        secondary: '#7b5800',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdc34d',
        'on-secondary-container': '#715000',
        'secondary-fixed': '#ffdea6',
        'secondary-fixed-dim': '#f7bd48',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5d4200',
        tertiary: '#2e2d29',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#44433e',
        'on-tertiary-container': '#b2b0a9',
        'tertiary-fixed': '#e6e2db',
        'tertiary-fixed-dim': '#c9c6c0',
        'on-tertiary-fixed': '#1c1c18',
        'on-tertiary-fixed-variant': '#484742',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf9f8',
        'on-background': '#1c1b1b',
        'surface-variant': '#e5e2e1',
        'aged-paper': '#D4C9A8',
        'elevated-panels': '#F5EFE0',
        parchment: '#FAF6EF',
        'forest-green': '#033327',
        'gilt-gold': '#B8860B',
        ink: '#1c1b1b',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        serif: ['Lora', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'body-lg': ['Literata', 'Georgia', 'serif'],
        'body-md': ['Literata', 'Georgia', 'serif'],
        'display-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg': ['"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['"Playfair Display"', 'Georgia', 'serif'],
        'label-sm': ['Literata', 'Georgia', 'serif'],
        'code-sm': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        editor: ['Lora', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        content: '800px',
      },
    },
  },
  plugins: [],
}

export default config
